#!/bin/bash

type=$1
dir=$2
file_name=$3

to_pascal_case() {
    local inputString=$file_name
    local baseName=${inputString%.*}
    local words=$(echo "$baseName" | sed 's/[^a-zA-Z0-9]/ /g')

    local pascalCaseOutput=""
    for word in $words; do
      pascalCaseOutput+=${word^}
    done

    echo $(echo "$pascalCaseOutput" | sed 's/ //g')
}

initLayout=$(cat << 'EndOfText'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
EndOfText
)

initPage=$(cat << 'EndOfText'
import React from "react";

const Home = () => (
  <div className="App">
    HOME
  </div>
);

export default Home;

EndOfText
)

componentName=$(to_pascal_case)
initEmptyComponent=$(cat << EndOfText
import React from "react";

const ${componentName} = () => (
  <div className="App">
    COMPONENT
  </div>
);

export default ${componentName};

EndOfText
)

initServices=$(cat << EndOfText
import { getCookies } from "@/utils/cookies";

const service: string | undefined = process.env.URI_API;
const version: string | undefined = process.env.URI_VER;
EndOfText
)

initInterface=$(cat << EndOfTime
EndOfTime
)

function app_layout() {
    mkdir ./src/app/$dir
    # touch ./src/app/$dir/layout.tsx ./src/app/$dir/page.tsx
    echo -e "$initLayout" > ./src/app/$dir/layout.tsx
    echo -e "$initPage" > ./src/app/$dir/page.tsx
    echo -e "$initInterface" > ./src/app/$dir/interface.tsx
    echo -e "$initServices" > ./src/app/$dir/services.tsx

    zeditor --add ./src/app/$dir/layout.tsx ./src/app/$dir/page.tsx
}

function cmp_layout() {
    mkdir ./src/components/$dir
    # touch ./src/components/$dir/$file_name
    echo -e "$initEmptyComponent" > ./src/components/$dir/$file_name

    zeditor --add ./src/components/$dir/$file_name
}

if [[ $type != 'app' && $type != 'cmp' ]];
then
    echo "Entrada no valida"
fi

if [[ $type == 'app' ]];
then
    app_layout
fi

if [[ $type == 'cmp' ]];
then
    cmp_layout
fi
